
package rik.kinniskrteenused;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "KR_teenusSoap", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KRTeenusSoap {


    /**
     * 
     * @param parool
     * @param kehtivadKehtetud
     * @param perenimiFirma
     * @param kood
     * @param eesnimi
     * @param kasutajanimi
     * @return
     *     returns ee.rik.kinnistusraamat.krteenused.KRIsikuKinnistudV4
     */
    @WebMethod(operationName = "kR_isiku_kinnistud_v4", action = "http://kinnistusraamat.rik.ee/krteenused/kR_isiku_kinnistud_v4")
    @WebResult(name = "kR_isiku_kinnistud_v4Result", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
    @RequestWrapper(localName = "kR_isiku_kinnistud_v4", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/", className = "ee.rik.kinnistusraamat.krteenused.KRIsikuKinnistudV42")
    @ResponseWrapper(localName = "kR_isiku_kinnistud_v4Response", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/", className = "ee.rik.kinnistusraamat.krteenused.KRIsikuKinnistudV4Response")
    public KRIsikuKinnistudV4 kRIsikuKinnistudV4(
            @WebParam(name = "kood", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String kood,
            @WebParam(name = "eesnimi", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String eesnimi,
            @WebParam(name = "perenimi_firma", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String perenimiFirma,
            @WebParam(name = "kehtivad_kehtetud", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String kehtivadKehtetud,
            @WebParam(name = "kasutajanimi", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String kasutajanimi,
            @WebParam(name = "parool", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String parool);

    /**
     *
     * @param parool
     * @param perenimiFirma
     * @param kood
     * @param eesnimi
     * @param kasutajanimi
     * @return
     *     returns ee.rik.kinnistusraamat.krteenused.ObjektideArv
     */
    @WebMethod(operationName = "objektide_arv", action = "http://kinnistusraamat.rik.ee/krteenused/objektide_arv")
    @WebResult(name = "objektide_arvResult", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
    @RequestWrapper(localName = "objektide_arv", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/", className = "ee.rik.kinnistusraamat.krteenused.ObjektideArv2")
    @ResponseWrapper(localName = "objektide_arvResponse", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/", className = "ee.rik.kinnistusraamat.krteenused.ObjektideArvResponse")
    public ObjektideArv objektideArv(
            @WebParam(name = "kood", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String kood,
            @WebParam(name = "eesnimi", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String eesnimi,
            @WebParam(name = "perenimi_firma", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String perenimiFirma,
            @WebParam(name = "kasutajanimi", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String kasutajanimi,
            @WebParam(name = "parool", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String parool);

    /**
     *
     * @param parool
     * @param kasLisainfo
     * @param kehtivadKehtetud
     * @param registriosaNr
     * @param koguRo
     * @param jagu2
     * @param kasutajanimi
     * @param jagu1
     * @param jagu34
     * @return
     *     returns ee.rik.kinnistusraamat.krteenused.KinnistuDetail
     */
    @WebMethod(operationName = "kinnistu_detail", action = "http://kinnistusraamat.rik.ee/krteenused/kinnistu_detail")
    @WebResult(name = "kinnistu_detailResult", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
    @RequestWrapper(localName = "kinnistu_detail", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/", className = "ee.rik.kinnistusraamat.krteenused.KinnistuDetail2")
    @ResponseWrapper(localName = "kinnistu_detailResponse", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/", className = "ee.rik.kinnistusraamat.krteenused.KinnistuDetailResponse")
    public KinnistuDetail kinnistuDetail(
            @WebParam(name = "registriosa_nr", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String registriosaNr,
            @WebParam(name = "kehtivad_kehtetud", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String kehtivadKehtetud,
            @WebParam(name = "kas_lisainfo", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String kasLisainfo,
            @WebParam(name = "kogu_ro", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String koguRo,
            @WebParam(name = "jagu_1", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String jagu1,
            @WebParam(name = "jagu_2", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String jagu2,
            @WebParam(name = "jagu_3_4", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String jagu34,
            @WebParam(name = "kasutajanimi", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String kasutajanimi,
            @WebParam(name = "parool", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String parool);

    /**
     *
     * @param parool
     * @param kasLisainfo
     * @param kehtivadKehtetud
     * @param registriosaNr
     * @param koguRo
     * @param jagu2
     * @param kasutajanimi
     * @param jagu1
     * @param jagu34
     * @return
     *     returns ee.rik.kinnistusraamat.krteenused.KinnistuDetailV22
     */
    @WebMethod(operationName = "kinnistu_detail_v2", action = "http://kinnistusraamat.rik.ee/krteenused/kinnistu_detail_v2")
    @WebResult(name = "kinnistu_detail_v2Result", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
    @RequestWrapper(localName = "kinnistu_detail_v2", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/", className = "ee.rik.kinnistusraamat.krteenused.KinnistuDetailV2")
    @ResponseWrapper(localName = "kinnistu_detail_v2Response", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/", className = "ee.rik.kinnistusraamat.krteenused.KinnistuDetailV2Response")
    public KinnistuDetailV22 kinnistuDetailV2(
            @WebParam(name = "registriosa_nr", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String registriosaNr,
            @WebParam(name = "kehtivad_kehtetud", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String kehtivadKehtetud,
            @WebParam(name = "kas_lisainfo", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String kasLisainfo,
            @WebParam(name = "kogu_ro", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String koguRo,
            @WebParam(name = "jagu_1", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String jagu1,
            @WebParam(name = "jagu_2", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String jagu2,
            @WebParam(name = "jagu_3_4", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String jagu34,
            @WebParam(name = "kasutajanimi", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String kasutajanimi,
            @WebParam(name = "parool", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String parool);

    /**
     *
     * @param parool
     * @param kasLisainfo
     * @param kehtivadKehtetud
     * @param registriosaNr
     * @param koguRo
     * @param jagu2
     * @param kasutajanimi
     * @param jagu1
     * @param jagu34
     * @return
     *     returns ee.rik.kinnistusraamat.krteenused.KinnistuDetailV3
     */
    @WebMethod(operationName = "kinnistu_detail_v3", action = "http://kinnistusraamat.rik.ee/krteenused/kinnistu_detail_v3")
    @WebResult(name = "kinnistu_detail_v3Result", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
    @RequestWrapper(localName = "kinnistu_detail_v3", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/", className = "ee.rik.kinnistusraamat.krteenused.KinnistuDetailV32")
    @ResponseWrapper(localName = "kinnistu_detail_v3Response", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/", className = "ee.rik.kinnistusraamat.krteenused.KinnistuDetailV3Response")
    public KinnistuDetailV3 kinnistuDetailV3(
            @WebParam(name = "registriosa_nr", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String registriosaNr,
            @WebParam(name = "kehtivad_kehtetud", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String kehtivadKehtetud,
            @WebParam(name = "kas_lisainfo", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String kasLisainfo,
            @WebParam(name = "kogu_ro", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String koguRo,
            @WebParam(name = "jagu_1", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String jagu1,
            @WebParam(name = "jagu_2", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String jagu2,
            @WebParam(name = "jagu_3_4", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String jagu34,
            @WebParam(name = "kasutajanimi", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String kasutajanimi,
            @WebParam(name = "parool", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String parool);

    /**
     *
     * @param katastritunnus
     * @param parool
     * @param kasutajanimi
     * @return
     *     returns ee.rik.kinnistusraamat.krteenused.KRIsikuKinnistud
     */
    @WebMethod(operationName = "KR_katastriyksuse_kinnistud", action = "http://kinnistusraamat.rik.ee/krteenused/KR_katastriyksuse_kinnistud")
    @WebResult(name = "KR_katastriyksuse_kinnistudResult", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
    @RequestWrapper(localName = "KR_katastriyksuse_kinnistud", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/", className = "ee.rik.kinnistusraamat.krteenused.KRKatastriyksuseKinnistud")
    @ResponseWrapper(localName = "KR_katastriyksuse_kinnistudResponse", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/", className = "ee.rik.kinnistusraamat.krteenused.KRKatastriyksuseKinnistudResponse")
    public KRIsikuKinnistud krKatastriyksuseKinnistud(
            @WebParam(name = "katastritunnus", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String katastritunnus,
            @WebParam(name = "kasutajanimi", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String kasutajanimi,
            @WebParam(name = "parool", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String parool);

    /**
     *
     * @param katastritunnus
     * @param parool
     * @param kasutajanimi
     * @return
     *     returns ee.rik.kinnistusraamat.krteenused.KRIsikuKinnistudV2
     */
    @WebMethod(operationName = "KR_katastriyksuse_kinnistud_v2", action = "http://kinnistusraamat.rik.ee/krteenused/KR_katastriyksuse_kinnistud_v2")
    @WebResult(name = "KR_katastriyksuse_kinnistud_v2Result", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
    @RequestWrapper(localName = "KR_katastriyksuse_kinnistud_v2", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/", className = "ee.rik.kinnistusraamat.krteenused.KRKatastriyksuseKinnistudV2")
    @ResponseWrapper(localName = "KR_katastriyksuse_kinnistud_v2Response", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/", className = "ee.rik.kinnistusraamat.krteenused.KRKatastriyksuseKinnistudV2Response")
    public KRIsikuKinnistudV2 krKatastriyksuseKinnistudV2(
            @WebParam(name = "katastritunnus", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String katastritunnus,
            @WebParam(name = "kasutajanimi", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String kasutajanimi,
            @WebParam(name = "parool", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String parool);

    /**
     *
     * @param katastritunnus
     * @param parool
     * @param kasutajanimi
     * @return
     *     returns ee.rik.kinnistusraamat.krteenused.KRIsikuKinnistudV3
     */
    @WebMethod(operationName = "KR_katastriyksuse_kinnistud_v3", action = "http://kinnistusraamat.rik.ee/krteenused/KR_katastriyksuse_kinnistud_v3")
    @WebResult(name = "KR_katastriyksuse_kinnistud_v3Result", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
    @RequestWrapper(localName = "KR_katastriyksuse_kinnistud_v3", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/", className = "ee.rik.kinnistusraamat.krteenused.KRKatastriyksuseKinnistudV3")
    @ResponseWrapper(localName = "KR_katastriyksuse_kinnistud_v3Response", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/", className = "ee.rik.kinnistusraamat.krteenused.KRKatastriyksuseKinnistudV3Response")
    public KRIsikuKinnistudV3 krKatastriyksuseKinnistudV3(
            @WebParam(name = "katastritunnus", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String katastritunnus,
            @WebParam(name = "kasutajanimi", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String kasutajanimi,
            @WebParam(name = "parool", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/")
                    String parool);

}
