
package rik.kinniskrteenused;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "KR_teenus", targetNamespace = "http://kinnistusraamat.rik.ee/krteenused/", wsdlLocation = "https://kinnistusraamat.rik.ee/krteenused/kr_teenus.asmx?WSDL")
public class KRTeenus
    extends Service
{

    private final static URL KRTEENUS_WSDL_LOCATION;
    private final static WebServiceException KRTEENUS_EXCEPTION;
    private final static QName KRTEENUS_QNAME = new QName("http://kinnistusraamat.rik.ee/krteenused/", "KR_teenus");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://kinnistusraamat.rik.ee/krteenused/kr_teenus.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KRTEENUS_WSDL_LOCATION = url;
        KRTEENUS_EXCEPTION = e;
    }

    public KRTeenus() {
        super(__getWsdlLocation(), KRTEENUS_QNAME);
    }

    public KRTeenus(WebServiceFeature... features) {
        super(__getWsdlLocation(), KRTEENUS_QNAME, features);
    }

    public KRTeenus(URL wsdlLocation) {
        super(wsdlLocation, KRTEENUS_QNAME);
    }

    public KRTeenus(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KRTEENUS_QNAME, features);
    }

    public KRTeenus(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KRTeenus(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns KRTeenusSoap
     */
    @WebEndpoint(name = "KR_teenusSoap")
    public KRTeenusSoap getKRTeenusSoap() {
        return super.getPort(new QName("http://kinnistusraamat.rik.ee/krteenused/", "KR_teenusSoap"), KRTeenusSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KRTeenusSoap
     */
    @WebEndpoint(name = "KR_teenusSoap")
    public KRTeenusSoap getKRTeenusSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://kinnistusraamat.rik.ee/krteenused/", "KR_teenusSoap"), KRTeenusSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KRTEENUS_EXCEPTION!= null) {
            throw KRTEENUS_EXCEPTION;
        }
        return KRTEENUS_WSDL_LOCATION;
    }

}
