"""URL mapping for the ForestIQ-compatible REST interface."""

from django.urls import path

from . import auth, views

urlpatterns = [
    path("password-login", auth.password_login),
    path("services/totp", auth.totp_login),
    path("services/token-refresh", auth.refresh_token),
    path("services/change-my-password", auth.change_my_password),
    path("services/status", views.service_status),
    path("services/admin/users", views.admin_users),
    path("services/admin/users/<str:user_id>", views.admin_user_detail),
    path("services/admin/userstatistics/prep-data", views.user_statistics_prep),
    path("services/admin/userstatistics/owner-status-change", views.user_statistics),
    path("services/owner-statuses", views.owner_statuses),
    path("services/owner-statuses/<str:status_id>", views.owner_status_detail),
    path("services/admin-workdesk/prepare", views.admin_workdesk_prep),
    path("services/admin-workdesk/owners-search", views.admin_workdesk_search),
    path("services/admin-workdesk/assign", views.admin_workdesk_assign),
    path("services/contract-starter", views.contract_starter),
    path("services/contracts", views.contracts),
    path("services/contracts/<str:contract_id>", views.contract_detail),
    path("services/contracts/<str:contract_id>/pdf", views.contract_pdf),
    path("services/contracts/suggestors/cadastre/<str:cadastre_id>", views.contract_cadastre_suggest),
    path("services/contracts/cadastre-details/<str:cadastre_id>", views.cadastre_detail),
    path("services/contracts/suggestors/owner/<str:owner_id>", views.contract_owner_suggest),
    path("services/contracts/owner-details/<str:owner_id>", views.owner_detail),
    path("services/owners", views.owner_list),
    path("services/owners-in-need-of-evaluation", views.owners_in_need_of_evaluation),
    path("services/owners/<str:owner_id>", views.owner_detail),
    path("services/owners/<str:owner_id>/add", views.owner_add),
    path("services/owners/<str:owner_id>/change-status", views.owner_status),
    path("services/owners/<str:owner_id>/mark-cadastres", views.mark_cadastres),
    path("services/owners/<str:owner_id>/log", views.owner_log),
    path("services/owner/<str:owner_id>/status", views.owner_status),
    path("services/owner/<str:owner_id>/assignee", views.owner_assignee),
    path("services/owner/<str:owner_id>/followings", views.owner_followings),
    path("services/owner/<str:owner_id>/followings/<str:user_id>", views.owner_following_detail),
    path("services/cadastres/<str:cadastre_id>", views.cadastre_detail),
    path("services/cadastres/<str:cadastre_id>/evaluation", views.cadastre_evaluation),
    path("services/cadastres/<str:cadastre_id>/labels", views.cadastre_label),
    path("services/cadastres/<str:cadastre_id>/labels/<str:label>", views.cadastre_label),
    path("services/cadastres/<str:cadastre_id>/notifications", views.cadastre_notifications),
    path("services/cadastres/<str:cadastre_id>/mkdata", views.cadastre_mkdata),
    path("services/cadastres/<str:cadastre_id>/areas", views.cadastre_areas),
    path("services/cadastres/<str:cadastre_id>/registry-features", views.registry_features),
    path("services/my-work", views.my_work),
    path("services/my-work/next-owner", views.next_owner),
    path("services/caller-workdesk-prep-data", views.caller_workdesk_prep),
    path("services/reminders", views.reminders),
    path("services/reminders/<int:reminder_id>", views.reminder_detail),
    path("services/reminders-dashboard", views.reminders_dashboard),
    path("services/persons-dump", views.persons_dump),
    path("services/persons-dump/<int:person_id>", views.persons_dump_detail),
    path("services/messages/received", views.received_messages),
    path("services/messages/sent", views.sent_messages),
    path("services/messages/send", views.send_message),
    path("services/messages/read", views.mark_messages_read),
    path("services/messages/received/mark-as-read", views.mark_messages_read),
    path("services/messages/users", views.message_users),
    path("services/messages/usernames", views.message_users),
    path("services/messages/new-count", views.new_messages_count),
    path("services/messages/new/count", views.new_messages_count),
]
