# Generated by Django 5.2.17 on 2026-08-26 07:47

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


LEGACY_ORGANIZATION_ID = uuid.UUID("00000000-0000-4000-8000-000000000001")
LEGACY_ORGANIZATION_SLUG = "forestiq-default"
LEGACY_ORGANIZATION_NAME = "ForestIQ legacy organization"


def create_legacy_organization(apps, schema_editor):
    """Create the explicit owner used to backfill all pre-tenancy rows."""

    Organization = apps.get_model("accounts", "Organization")
    Organization.objects.get_or_create(
        id=LEGACY_ORGANIZATION_ID,
        defaults={"slug": LEGACY_ORGANIZATION_SLUG, "name": LEGACY_ORGANIZATION_NAME, "is_active": True},
    )


def backfill_organization_memberships(apps, schema_editor):
    """Make every existing user a member of its migrated default organization."""

    User = apps.get_model("accounts", "User")
    OrganizationMembership = apps.get_model("accounts", "OrganizationMembership")
    OrganizationMembership.objects.bulk_create(
        [
            OrganizationMembership(organization_id=user.default_organization_id, user_id=user.id)
            for user in User.objects.iterator()
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.RunPython(create_legacy_organization, migrations.RunPython.noop),
        migrations.AddField(
            model_name='user',
            name='default_organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.PROTECT, related_name='default_users', to='accounts.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_memberships',
            },
        ),
        migrations.RunPython(backfill_organization_memberships, migrations.RunPython.noop),
        migrations.AddField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(related_name='users', through='accounts.OrganizationMembership', to='accounts.organization'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user', 'organization'], name='org_member_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_membership'),
        ),
    ]
