# Generated by Django 5.2.17 on 2026-08-26
from django.db import migrations, models
from django.utils import timezone


def backfill_membership_roles(apps, schema_editor):
    """Preserve existing privileges by deriving equivalent organization roles."""
    Membership = apps.get_model("accounts", "OrganizationMembership")
    Privilege = apps.get_model("accounts", "Privilege")

    privileges_by_user = {}
    for user_id, code in Privilege.objects.values_list("user_id", "code"):
        privileges_by_user.setdefault(user_id, set()).add(code)

    for membership in Membership.objects.iterator():
        granted = privileges_by_user.get(membership.user_id, set())
        roles = ["ORG_MEMBER"]
        if "ADMIN" in granted:
            roles.append("ORG_ADMIN")
        if "OWNER_PROFILE" in granted:
            roles.append("CRM_MANAGER")
        if "EVALUATION" in granted:
            roles.append("EVALUATOR")
        if {"ASSIGNED_OWNERS", "PHONES"}.intersection(granted):
            roles.append("CALLER")
        membership.roles = roles
        membership.oidc_managed = False
        membership.save(update_fields=["roles", "oidc_managed", "updated_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_organization_user_default_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmembership",
            name="roles",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="oidc_managed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_membership_roles, migrations.RunPython.noop),
    ]
