# Generated by Django 5.2.17 on 2026-08-26
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_organization_membership_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="oidc_subject",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
