/** ForestIQ Landscape Desk design: owners are scanned in a field-log table, then opened in context. */
import { useEffect, useMemo, useState } from "react";
import { Filter, Search, SlidersHorizontal, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { AppShell } from "@/components/AppShell";
import { StatusPill } from "@/components/StatusPill";
import { api } from "@/lib/api";
import type { Owner } from "@/lib/types";
export default function Owners() { const [owners, setOwners] = useState<Owner[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); useEffect(() => { setLoading(true); api.get<Owner[]>("/services/owners").then(setOwners).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, []); const shown = useMemo(() => owners.filter((owner) => `${owner.name} ${owner.id} ${owner.phone || ""}`.toLowerCase().includes(query.toLowerCase())), [owners, query]); return <AppShell title="Omanikud" eyebrow="FORESTIQ / OMANIKE REGISTER"><section className="section-lead"><div><p>Leia kontakt, ava katastri seosed ning registreeri järgmine otsus.</p><strong><UsersRound size={17} /> {owners.length} kirjet</strong></div><div className="search-bar"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Otsi nime, isikukoodi või telefoni järgi" /><button aria-label="Filtreeri"><SlidersHorizontal size={18} /></button></div></section>{error && <div className="connection-warning">{error}</div>}<section className="table-panel"><div className="table-toolbar"><span><Filter size={16} /> Kõik aktiivsed tulemused</span><small>Klõpsa real, et avada töökaart</small></div><div className="data-table"><div className="table-head"><span>Omanik</span><span>Kontakt</span><span>Staatus</span><span>Määratud</span><span /></div>{shown.map((owner) => <Link key={owner.id} href={`/owners/${owner.id}`} className="table-row"><span className="owner-cell"><i /><b>{owner.name}</b><small>{owner.id}</small></span><span><b>{owner.phone || "—"}</b><small>{owner.email || "e-post puudub"}</small></span><span><StatusPill value={owner.status} /></span><span>{owner.assignee?.name || "Määramata"}</span><span>→</span></Link>)}{loading && <div className="empty-state">Laadin omanike registrit…</div>}{!loading && !shown.length && <div className="empty-state">Selle otsinguga omanikke ei leitud.</div>}</div></section></AppShell>; }
