import { useEffect, useState } from "react";
import { AlertTriangle, BadgeEuro, FileUp, Gauge, Gavel, RefreshCw, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { AppShell } from "@/components/AppShell";
import { api } from "@/lib/api";
import type { Deal, InheritanceCase, IntegrationJob, SalesTask } from "@/lib/types";

function ErrorNotice({ error }: { error: string }) { return error ? <div className="connection-warning">{error}</div> : null; }
function Money({ value }: { value?: number | null }) { return value == null ? <>—</> : <>{new Intl.NumberFormat("et-EE", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(value)}</>; }

export function DealsWorkspace() { const [deals, setDeals] = useState<Deal[]>([]); const [error, setError] = useState(""); useEffect(() => { api.get<Deal[]>("/services/deals/evaluation-queue").then(setDeals).catch((err) => setError(err.message)); }, []); return <AppShell title="Hindamise ja tehingute järjekord" eyebrow="KOMMERTS / HINDAMINE"><section className="workspace-intro"><BadgeEuro size={24} /><div><h2>Hinnatavad metsa- ja maatehingud</h2><p>Võta hindamine enda tööks või ava omanik, et vormistada pakkumine ja sulgeda tehing.</p></div><div className="workspace-count">{deals.length}<small>tehingut</small></div></section><ErrorNotice error={error} /><section className="work-card-grid">{deals.map((deal) => <Link href={`/owners/${deal.owner.id}`} key={deal.id} className="work-card"><div><span className="status-pill">{deal.stage.replaceAll("_", " ")}</span><h3>{deal.owner.name}</h3><p>{deal.saleSubject} · {deal.parcels.length} kinnistut · <Money value={deal.priceExpectation} /></p></div><span>AVA TEHING →</span></Link>)}{!deals.length && <div className="empty-state">Hindamisjärjekord on tühi või sul pole selle vaate õigust.</div>}</section></AppShell>; }

export function InheritanceWorkspace() { const [cases, setCases] = useState<InheritanceCase[]>([]); const [error, setError] = useState(""); useEffect(() => { api.get<InheritanceCase[]>("/services/inheritance/cases").then(setCases).catch((err) => setError(err.message)); }, []); return <AppShell title="Pärimisjuhtumid" eyebrow="JUHTUMID / PÄRIMINE"><section className="workspace-intro"><Gavel size={24} /><div><h2>Pärimisteadete ja pärijate tööjärjekord</h2><p>Juhtumid põhinevad imporditud ametlikel teadetel ning jäävad omanikukaardiga seotuks.</p></div><div className="workspace-count">{cases.length}<small>juhtumit</small></div></section><ErrorNotice error={error} /><section className="work-card-grid">{cases.map((item) => <Link href={`/inheritance/${item.id}`} key={item.id} className="work-card"><div><span className="status-pill">{item.status.replaceAll("_", " ")}</span><h3>{item.owner.name}</h3><p>{item.sourceNoticeNumber || "teate number puudub"} · {item.heirs.length} pärijat</p></div><span>AVA JUHTUM →</span></Link>)}{!cases.length && <div className="empty-state">Pärimisjuhtumeid ei ole või ligipääs puudub.</div>}</section></AppShell>; }

export function SalesWorkspace() { const [tasks, setTasks] = useState<SalesTask[]>([]); const [error, setError] = useState(""); const refresh = () => api.get<SalesTask[]>("/services/sales-workspace/queue").then(setTasks).catch((err) => setError(err.message)); useEffect(() => { void refresh(); }, []); const outcome = async (ownerId: string, value: string) => { try { await api.post(`/services/sales-workspace/owners/${ownerId}/outcome`, { outcome: value }); void refresh(); } catch (err) { setError(err instanceof Error ? err.message : "Tulemust ei saanud salvestada."); } }; return <AppShell title="Müügitöö järjekord" eyebrow="KOMMERTS / KONTAKTID"><section className="workspace-intro"><UsersRound size={24} /><div><h2>Prioriseeritud kontaktid ja järgmised tegevused</h2><p>Salvesta standardne kontaktitulemus; tagasihelistamistele luuakse automaatselt meeldetuletus.</p></div><div className="workspace-count">{tasks.length}<small>kontakti</small></div></section><ErrorNotice error={error} /><section className="work-card-grid">{tasks.map((task) => <article key={task.owner.id} className="work-card"><div><span className="status-pill">{task.openDealCount} avatud tehingut</span><h3>{task.owner.name}</h3><p>{task.markedParcelCount} märgitud kinnistut</p></div><div className="flex flex-wrap gap-2"><button className="secondary-action" onClick={() => outcome(task.owner.id, "CALLBACK")}>Helista tagasi</button><button className="secondary-action" onClick={() => outcome(task.owner.id, "INTERESTED")}>Huvitatud</button><Link href={`/owners/${task.owner.id}`}>AVA →</Link></div></article>)}{!tasks.length && <div className="empty-state">Müügitöö järjekord on tühi.</div>}</section></AppShell>; }

export function IntegrationsWorkspace() { const [jobs, setJobs] = useState<IntegrationJob[]>([]); const [freshness, setFreshness] = useState<{ totalCadastres: number; staleCadastres: number; recentFailures: number } | null>(null); const [error, setError] = useState(""); const refresh = () => Promise.all([api.get<IntegrationJob[]>("/services/admin/integrations"), api.get<{ totalCadastres: number; staleCadastres: number; recentFailures: number }>("/services/registry/freshness")]).then(([jobData, fresh]) => { setJobs(jobData); setFreshness(fresh); }).catch((err) => setError(err.message)); useEffect(() => { void refresh(); }, []); const run = async (key: string) => { try { await api.post(`/services/admin/integrations/${key}/runs`, {}); void refresh(); } catch (err) { setError(err instanceof Error ? err.message : "Integratsiooni ei saanud käivitada."); } }; const recover = async () => { try { await api.post("/services/registry/freshness/recover", { batchSize: 25 }); void refresh(); } catch (err) { setError(err instanceof Error ? err.message : "Taastamist ei saanud käivitada."); } }; return <AppShell title="Integratsioonide ja värskuse haldus" eyebrow="HALDUS / ANDMEVOOD"><section className="workspace-intro"><Gauge size={24} /><div><h2>Välisandmete tervis ja auditeeritud käivitused</h2><p>Kontrolli katastri, omandisuhete ja pärimisteadete värskust ning käivita lubatud töid.</p></div><button className="secondary-action" onClick={recover}><RefreshCw size={16} /> Taasta aegunud</button></section><ErrorNotice error={error} />{freshness && <section className="metrics-grid"><div className="metric-card"><span>Katastriüksusi</span><strong>{freshness.totalCadastres}</strong></div><div className="metric-card"><span>Aegunud</span><strong>{freshness.staleCadastres}</strong></div><div className="metric-card"><span>Tõrkeid</span><strong>{freshness.recentFailures}</strong></div></section>}<section className="work-card-grid">{jobs.map((job) => <article key={job.key} className="work-card"><div><span className={`status-pill ${job.configured ? "" : "warning"}`}>{job.configured ? "SEADISTATUD" : "OPT-IN"}</span><h3>{job.label}</h3><p>{job.lastRun ? `${job.lastRun.status} · ${job.lastRun.error || "viimane käivitus"}` : "Käivitusi pole"}</p></div><button className="secondary-action" onClick={() => run(job.key)}><RefreshCw size={16} /> Käivita</button></article>)}{!jobs.length && <div className="empty-state"><AlertTriangle size={18} /> Integratsiooniandmed puuduvad.</div>}</section></AppShell>; }

export function OwnerImportWorkspace() { const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<{ sha256: string; readyCount: number; rejectedCount: number; rows: { rowNumber: number; id: string; name: string; status: string; reason: string }[] } | null>(null); const [error, setError] = useState(""); const inspect = async () => { if (!file) return; const form = new FormData(); form.append("file", file); try { const data = await api.upload<{ suggestedMapping: Record<string, string> }>("/services/owners/imports/inspect", form); const check = new FormData(); check.append("file", file); check.append("mapping", JSON.stringify(data.suggestedMapping)); setPreview(await api.upload("/services/owners/imports/preview", check)); } catch (err) { setError(err instanceof Error ? err.message : "Faili kontrollimine ebaõnnestus."); } }; const commit = async () => { if (!file || !preview) return; const form = new FormData(); form.append("file", file); form.append("confirmedSha256", preview.sha256); try { await api.upload("/services/owners/imports/commit", form); setFile(null); setPreview(null); } catch (err) { setError(err instanceof Error ? err.message : "Import ebaõnnestus."); } }; return <AppShell title="Omanike import" eyebrow="HALDUS / ANDMEIMPORT"><section className="workspace-intro"><FileUp size={24} /><div><h2>Kontrollitud CSV- ja XLSX-import</h2><p>Vaata enne salvestamist veerumappingut, duplikaate ning vigaseid ridu.</p></div></section><ErrorNotice error={error} /><section className="panel p-6"><input type="file" accept=".csv,.xlsx" onChange={(event) => { setFile(event.target.files?.[0] || null); setPreview(null); }} /><div className="mt-4 flex gap-3"><button className="secondary-action" disabled={!file} onClick={inspect}>Kontrolli faili</button><button className="secondary-action" disabled={!preview || !preview.readyCount} onClick={commit}>Impordi {preview?.readyCount || 0} rida</button></div>{preview && <div className="mt-6"><p className="eyebrow">EELVAADE</p><h3>{preview.readyCount} valmis · {preview.rejectedCount} tagasi lükatud</h3><div className="mt-4 space-y-2">{preview.rows.slice(0, 20).map((row) => <div key={row.rowNumber} className="flex items-center justify-between rounded-lg bg-muted px-3 py-2 text-sm"><span>{row.rowNumber}. {row.name || row.id || "Tühi rida"}</span><span>{row.status}{row.reason ? ` — ${row.reason}` : ""}</span></div>)}</div></div>}</section></AppShell>; }
