/** ForestIQ Landscape Desk design: reusable workbench handles caller, evaluator, contracts and contacts flows. */
import { useEffect, useState } from "react";
import { BarChart3, ClipboardCheck, FileStack, PhoneCall, Search, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { AppShell } from "@/components/AppShell";
import { StatusPill } from "@/components/StatusPill";
import { api } from "@/lib/api";
import type { Owner } from "@/lib/types";
const config = { caller: { title: "Minu tööjärjekord", eyebrow: "TÖÖLAUD / HELISTAJA", endpoint: "/services/my-work", icon: ClipboardCheck, lead: "Täienda omanike töölogi ning vii iga kontakt järgmise otsuseni." }, evaluator: { title: "Hindamise töölaud", eyebrow: "TÖÖLAUD / HINDAJA", endpoint: "/services/owners-in-need-of-evaluation", icon: BarChart3, lead: "Need omanikud ootavad kinnistu ja pakkumise hindamist." }, admin: { title: "Tööde jaotamine", eyebrow: "TÖÖLAUD / HALDUS", endpoint: "/services/admin-workdesk/owners-search", icon: ShieldCheck, lead: "Otsi, filtreeri ja suuna omanike töö järgmisele vastutajale." } } as const;
export function OwnerWorkspace({ kind }: { kind: keyof typeof config }) { const current = config[kind]; const Icon = current.icon; const [owners, setOwners] = useState<Owner[]>([]); const [error, setError] = useState(""); useEffect(() => { api.get<Owner[]>(current.endpoint).then(setOwners).catch((err) => setError(err.message)); }, [current.endpoint]); return <AppShell title={current.title} eyebrow={current.eyebrow}><section className="workspace-intro"><Icon size={24} /><div><h2>{current.lead}</h2><p>Vali kirje, et avada detailne töökaart ja teha järgmine toiming.</p></div><div className="workspace-count">{owners.length}<small>tulemust</small></div></section>{error && <div className="connection-warning">{error}</div>}<section className="work-card-grid">{owners.map((owner) => <Link href={`/owners/${owner.id}`} key={owner.id} className="work-card"><div><StatusPill value={owner.status} /><h3>{owner.name}</h3><p>{owner.id}</p></div><span>AVA TÖÖKAART →</span></Link>)}{!owners.length && <div className="empty-state">Töölaud on tühi või õigused ei võimalda neid andmeid lugeda.</div>}</section></AppShell>; }
export function GenericWorkspace({ kind }: { kind: "contracts" | "phones" | "me" }) { const map = { contracts: ["Lepingute register", "LEPINGUD", FileStack, "/services/contracts"], phones: ["Kontaktide register", "KONTAKTID", PhoneCall, "/services/persons-dump"], me: ["Minu konto", "KASUTAJA", ShieldCheck, "/services/status"] } as const; const [title, eyebrow, Icon, endpoint] = map[kind]; const [records, setRecords] = useState<Record<string, unknown>[]>([]); const [error, setError] = useState(""); useEffect(() => { api.get<Record<string, unknown>[]>(endpoint).then((data) => setRecords(Array.isArray(data) ? data : [data])).catch((err) => setError(err.message)); }, [endpoint]); return <AppShell title={title} eyebrow={`FORESTIQ / ${eyebrow}`}><section className="workspace-intro"><Icon size={24} /><div><h2>{kind === "contracts" ? "Ajaloolised lepingud ja uue lepingu lähteandmed ühel tööpinnal." : kind === "phones" ? "Otsi ning halda metsandusega seotud kontaktide registrit." : "Halda oma sisselogimist ja turvaeelistusi."}</h2><p>Andmed pärinevad otse Django teenusest.</p></div></section>{error && <div className="connection-warning">{error}</div>}<section className="table-panel generic-records"><div className="table-toolbar"><span><Search size={16} /> {records.length} tulemust</span></div>{records.map((record, index) => <pre key={index}>{JSON.stringify(record, null, 2)}</pre>)}{!records.length && <div className="empty-state">Andmed puuduvad või pole seda vaadet veel õigustega avatud.</div>}</section></AppShell>; }
