#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/../django_backend"

: "${FORESTIQ_SOAK_WFS_ITERATIONS:=50}"
: "${FORESTIQ_SOAK_WFS_MAX_SECONDS:=5}"
: "${FORESTIQ_SOAK_HTTP_SAMPLES:=30}"
: "${FORESTIQ_SOAK_P95_MS:=750}"
: "${FORESTIQ_SOAK_P99_MS:=1200}"
: "${FORESTIQ_SOAK_MEMORY_MB:=128}"
: "${FORESTIQ_SOAK_DB_CONNECTION_GROWTH:=2}"
export FORESTIQ_SOAK_WFS_ITERATIONS FORESTIQ_SOAK_WFS_MAX_SECONDS FORESTIQ_SOAK_HTTP_SAMPLES
export FORESTIQ_SOAK_P95_MS FORESTIQ_SOAK_P99_MS FORESTIQ_SOAK_MEMORY_MB FORESTIQ_SOAK_DB_CONNECTION_GROWTH

python manage.py test forestry.tests_soak_performance --verbosity 2
