# Generated by Django 5.2.17 on 2026-08-22 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forestry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('document', models.BinaryField(blank=True, db_column='contract', null=True)),
                ('base_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sellers', models.CharField(max_length=1000)),
                ('buyer', models.CharField(max_length=100)),
                ('contract_number', models.CharField(db_column='contract_no', max_length=50)),
                ('created_at', models.DateTimeField(db_column='created')),
                ('data', models.JSONField(default=dict)),
                ('cadastres', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'contract_history',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PersonDump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'persons_dump',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ApplicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_column='message_text')),
                ('admin_message', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, db_column='recipient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_messages',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_column='message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('noticed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, db_column='recipient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_direct_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, db_column='sender', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_direct_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['recipient', 'noticed_at'], name='message_received_idx'), models.Index(fields=['sender', 'created_at'], name='message_sent_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_time', models.DateTimeField(db_column='duetime')),
                ('text', models.TextField(blank=True, db_column='reminder_text')),
                ('created_time', models.DateTimeField(auto_now_add=True, db_column='created_time')),
                ('cadastre', models.TextField(blank=True)),
                ('property_name', models.TextField(blank=True)),
                ('creator', models.ForeignKey(blank=True, db_column='creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reminders', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='forestry.owner')),
            ],
            options={
                'db_table': 'reminders',
                'ordering': ('due_time', 'id'),
                'indexes': [models.Index(fields=['due_time'], name='reminder_due_idx')],
            },
        ),
    ]
