# Generated by Django 5.2.17 on 2026-08-26 07:51

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_user_default_organization_and_more'),
        ('forestry', '0005_remove_cadastrelabel_unique_cadastre_label_and_more'),
        ('operations', '0004_deal_backed_contracts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dealoffer',
            name='unique_deal_offer_revision',
        ),
        migrations.RemoveIndex(
            model_name='deal',
            name='deal_owner_stage_idx',
        ),
        migrations.RemoveIndex(
            model_name='deal',
            name='deal_stage_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='directmessage',
            name='message_received_idx',
        ),
        migrations.RemoveIndex(
            model_name='directmessage',
            name='message_sent_idx',
        ),
        migrations.RemoveIndex(
            model_name='inheritancecase',
            name='inherit_case_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='ownershiptransitionevent',
            name='ownership_owner_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='reminder',
            name='reminder_due_idx',
        ),
        migrations.AddField(
            model_name='applicationmessage',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='contract',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='contracthistory',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='deal',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='dealoffer',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='inheritancecase',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='inheritancecaseevent',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='inheritanceheir',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='ownerimportbatch',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='ownershiptransitionevent',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='persondump',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddIndex(
            model_name='applicationmessage',
            index=models.Index(fields=['organization', 'recipient', 'created_at'], name='app_message_org_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'owner', 'stage'], name='deal_organization_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'stage', 'updated_at'], name='deal_organization_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['organization', 'recipient', 'noticed_at'], name='message_org_received_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['organization', 'sender', 'created_at'], name='message_organization_sent_idx'),
        ),
        migrations.AddIndex(
            model_name='inheritancecase',
            index=models.Index(fields=['organization', 'status', 'assigned_to'], name='inherit_case_organization_idx'),
        ),
        migrations.AddIndex(
            model_name='ownershiptransitionevent',
            index=models.Index(fields=['organization', 'owner', 'occurred_at'], name='ownership_org_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['organization', 'due_time'], name='reminder_organization_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='dealoffer',
            constraint=models.UniqueConstraint(fields=('organization', 'deal', 'revision'), name='unique_organization_deal_offer_revision'),
        ),
        migrations.AddConstraint(
            model_name='inheritancecase',
            constraint=models.UniqueConstraint(condition=models.Q(('source_notice_number', ''), _negated=True), fields=('organization', 'owner', 'source_notice_number'), name='unique_organization_inheritance_case'),
        ),
    ]
