# Generated by Django 5.2.17 on 2026-08-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_alter_applicationmessage_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='version',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deal',
            name='version',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inheritancecase',
            name='version',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
