# Generated by Django 5.2.17 on 2026-08-27 19:03

import accounts.models
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_oidc_subject'),
        ('operations', '0007_add_aggregate_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='template_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=255)),
                ('registry_code', models.CharField(blank=True, max_length=64)),
                ('vat_number', models.CharField(blank=True, max_length=64)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('iban', models.CharField(blank=True, max_length=64)),
                ('signatory_name', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'company_profiles',
                'ordering': ('legal_name', 'id'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('html', models.TextField()),
                ('version', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_templates', to='operations.companyprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contract_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successor_versions', to='operations.contracttemplate')),
            ],
            options={
                'db_table': 'contract_templates',
                'ordering': ('template_key', '-version'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='template_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_contracts', to='operations.contracttemplate'),
        ),
        migrations.AddConstraint(
            model_name='companyprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('registry_code', ''), _negated=True), fields=('organization', 'registry_code'), name='unique_organization_company_registry_code'),
        ),
        migrations.AddConstraint(
            model_name='contracttemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'template_key', 'version'), name='unique_organization_contract_template_version'),
        ),
        migrations.AddConstraint(
            model_name='contracttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization', 'template_key'), name='unique_active_organization_contract_template'),
        ),
    ]
