# Generated by Django 5.2.17 on 2026-08-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_oidc_subject'),
        ('forestry', '0011_add_gis_summary_indexes'),
        ('operations', '0008_contract_template_snapshot_companyprofile_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ownershiptransitionevent',
            constraint=models.UniqueConstraint(condition=models.Q(('source_reference__gt', '')), fields=('organization', 'source_reference'), name='ownership_event_source_reference_uniq'),
        ),
    ]
