# Generated by Django 5.2.17 on 2026-09-01

from django.db import migrations, models
from django.utils import timezone


def backfill_contract_created_at(apps, schema_editor):
    Contract = apps.get_model("operations", "Contract")
    ContractHistory = apps.get_model("operations", "ContractHistory")
    for contract in Contract.objects.filter(created_at__isnull=True).iterator():
        history = ContractHistory.objects.filter(id=contract.id).only("created_at").first()
        contract.created_at = history.created_at if history else timezone.now()
        contract.save(update_fields=("created_at",))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0009_ownership_event_source_idempotency"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archived")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(backfill_contract_created_at, noop_reverse),
        migrations.AlterField(
            model_name="contract",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
