# Generated for ForestIQ-D P1 workflows on 2026-09-17.
from __future__ import annotations

import uuid

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forestry", "0011_add_gis_summary_indexes"),
        ("operations", "0010_contract_retention_lifecycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactActivity",
            fields=[
                ("organization", models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="accounts.organization")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("channel", models.CharField(choices=[("PHONE", "Phone"), ("EMAIL", "Email"), ("MEETING", "Meeting")], max_length=20)),
                ("outcome_code", models.CharField(max_length=80)),
                ("outcome_reason", models.CharField(blank=True, max_length=255)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_contact_activities", to=settings.AUTH_USER_MODEL)),
                ("deal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="contact_activities", to="operations.deal")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contact_activities", to="forestry.owner")),
            ],
            options={"db_table": "p1_contact_activities", "ordering": ("-created_at", "-id")},
        ),
        migrations.CreateModel(
            name="DealWorkState",
            fields=[
                ("organization", models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="accounts.organization")),
                ("deal", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name="work_state", serialize=False, to="operations.deal")),
                ("evaluation_due_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "p1_deal_work_state"},
        ),
        migrations.CreateModel(
            name="LossReasonCode",
            fields=[
                ("organization", models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="accounts.organization")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "p1_loss_reason_codes", "ordering": ("sort_order", "label", "code")},
        ),
        migrations.CreateModel(
            name="ContractSigning",
            fields=[
                ("organization", models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="accounts.organization")),
                ("contract", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name="signing", serialize=False, to="operations.contract")),
                ("state", models.CharField(choices=[("PREPARING", "Preparing"), ("SENT_FOR_SIGNATURE", "Sent for signature"), ("SIGNED", "Signed"), ("CANCELLED", "Cancelled")], default="PREPARING", max_length=30)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("delay_reason", models.TextField(blank=True)),
                ("final_document", models.FileField(blank=True, null=True, upload_to="contract-signatures/%Y/%m")),
                ("final_url", models.URLField(blank=True, max_length=1000)),
                ("final_content_type", models.CharField(blank=True, max_length=120)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("responsible", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="responsible_contract_signings", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "p1_contract_signing"},
        ),
        migrations.CreateModel(
            name="OwnershipRelation",
            fields=[
                ("organization", models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="accounts.organization")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source", models.CharField(choices=[("LEGACY", "Legacy"), ("EXTERNAL", "External"), ("MANUAL", "Manual")], default="EXTERNAL", max_length=30)),
                ("source_reference", models.CharField(blank=True, max_length=255)),
                ("valid_from", models.DateTimeField(auto_now_add=True)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("ended_reason", models.TextField(blank=True)),
                ("manual_protected", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cadastre", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ownership_relations", to="forestry.cadastre")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_ownership_relations", to=settings.AUTH_USER_MODEL)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ownership_relations", to="forestry.owner")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_ownership_relations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "p1_ownership_relations", "ordering": ("-is_active", "owner_id", "cadastre_id", "-valid_from")},
        ),
        migrations.CreateModel(
            name="DataQualityIssue",
            fields=[
                ("organization", models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="accounts.organization")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("issue_type", models.CharField(max_length=80)),
                ("fingerprint", models.CharField(max_length=64)),
                ("severity", models.CharField(choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("CRITICAL", "Critical")], max_length=20)),
                ("description", models.TextField()),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("ASSIGNED", "Assigned"), ("RESOLVED", "Resolved")], default="OPEN", max_length=20)),
                ("resolution_note", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assignee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_quality_issues", to=settings.AUTH_USER_MODEL)),
                ("deal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="quality_issues", to="operations.deal")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="quality_issues", to="forestry.owner")),
                ("suggested_assignee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="suggested_quality_issues", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "p1_data_quality_issues", "ordering": ("-created_at", "id")},
        ),
        migrations.CreateModel(
            name="NextAction",
            fields=[
                ("organization", models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="accounts.organization")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=500)),
                ("due_at", models.DateTimeField()),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("DONE", "Done"), ("POSTPONED", "Postponed"), ("CANCELLED", "Cancelled")], default="OPEN", max_length=20)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assignee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assigned_next_actions", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_next_actions", to=settings.AUTH_USER_MODEL)),
                ("deal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="next_actions", to="operations.deal")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="next_actions", to="forestry.owner")),
                ("source_activity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="next_actions", to="operations.contactactivity")),
            ],
            options={"db_table": "p1_next_actions", "ordering": ("due_at", "id")},
        ),
        migrations.CreateModel(
            name="DealLossOutcome",
            fields=[
                ("organization", models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="accounts.organization")),
                ("deal", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name="structured_loss", serialize=False, to="operations.deal")),
                ("previous_stage", models.CharField(max_length=40)),
                ("note", models.TextField(blank=True)),
                ("follow_up_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="deal_outcomes", to="operations.lossreasoncode")),
                ("recorded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recorded_deal_losses", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "p1_deal_loss_outcomes"},
        ),
        migrations.CreateModel(
            name="ContractVersion",
            fields=[
                ("organization", models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="accounts.organization")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version_number", models.PositiveIntegerField()),
                ("pdf", models.BinaryField()),
                ("pdf_sha256", models.CharField(max_length=64)),
                ("snapshot", models.JSONField(default=dict)),
                ("checklist", models.JSONField(default=dict)),
                ("is_replacement", models.BooleanField(default=False)),
                ("change_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("contract", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="controlled_versions", to="operations.contract")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_contract_versions", to=settings.AUTH_USER_MODEL)),
                ("deal", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contract_versions", to="operations.deal")),
                ("offer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contract_versions", to="operations.dealoffer")),
                ("supersedes", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="replacements", to="operations.contractversion")),
            ],
            options={"db_table": "p1_contract_versions", "ordering": ("contract_id", "version_number")},
        ),
        migrations.CreateModel(
            name="ContractSigningEvent",
            fields=[
                ("organization", models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="accounts.organization")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("from_state", models.CharField(blank=True, max_length=30)),
                ("to_state", models.CharField(max_length=30)),
                ("reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="contract_signing_events", to=settings.AUTH_USER_MODEL)),
                ("signing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="operations.contractsigning")),
            ],
            options={"db_table": "p1_contract_signing_events", "ordering": ("created_at", "id")},
        ),
        migrations.CreateModel(
            name="DataQualityIssueEvent",
            fields=[
                ("organization", models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="accounts.organization")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=50)),
                ("reason", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="quality_issue_events", to=settings.AUTH_USER_MODEL)),
                ("issue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="operations.dataqualityissue")),
            ],
            options={"db_table": "p1_data_quality_events", "ordering": ("created_at", "id")},
        ),
        migrations.CreateModel(
            name="OwnershipRelationEvent",
            fields=[
                ("organization", models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="accounts.organization")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=80)),
                ("reason", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ownership_relation_events", to=settings.AUTH_USER_MODEL)),
                ("relation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="operations.ownershiprelation")),
            ],
            options={"db_table": "p1_ownership_relation_events", "ordering": ("created_at", "id")},
        ),
        migrations.CreateModel(
            name="WorkflowAuditEvent",
            fields=[
                ("organization", models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="accounts.organization")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=80)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_events", to="operations.contactactivity")),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workflow_audit_events", to=settings.AUTH_USER_MODEL)),
                ("deal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="workflow_events", to="operations.deal")),
                ("next_action", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_events", to="operations.nextaction")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="workflow_events", to="forestry.owner")),
            ],
            options={"db_table": "p1_workflow_audit", "ordering": ("-created_at", "-id")},
        ),
        migrations.AddConstraint(model_name="lossreasoncode", constraint=models.UniqueConstraint(fields=("organization", "code"), name="p1_uq_loss_reason_code")),
        migrations.AddConstraint(model_name="contractversion", constraint=models.UniqueConstraint(fields=("organization", "contract", "version_number"), name="p1_uq_contract_version")),
        migrations.AddConstraint(model_name="dataqualityissue", constraint=models.UniqueConstraint(fields=("organization", "fingerprint"), name="p1_uq_quality_fingerprint")),
        migrations.AddConstraint(model_name="ownershiprelation", constraint=models.UniqueConstraint(condition=models.Q(("is_active", True)), fields=("organization", "owner", "cadastre"), name="p1_uq_active_owner_cad")),
        migrations.AddIndex(model_name="contactactivity", index=models.Index(fields=["organization", "owner", "created_at"], name="p1_contact_owner_time_idx")),
        migrations.AddIndex(model_name="nextaction", index=models.Index(fields=["organization", "status", "due_at"], name="p1_action_status_due_idx")),
        migrations.AddIndex(model_name="nextaction", index=models.Index(fields=["organization", "assignee", "status"], name="p1_action_assignee_idx")),
        migrations.AddIndex(model_name="workflowauditevent", index=models.Index(fields=["organization", "owner", "created_at"], name="p1_workflow_owner_idx")),
        migrations.AddIndex(model_name="deallossoutcome", index=models.Index(fields=["organization", "created_at"], name="p1_loss_created_idx")),
        migrations.AddIndex(model_name="dataqualityissue", index=models.Index(fields=["organization", "status", "severity"], name="p1_quality_queue_idx")),
        migrations.AddIndex(model_name="ownershiprelation", index=models.Index(fields=["organization", "owner", "is_active"], name="p1_relation_owner_idx")),
    ]
