# Generated by Django 5.2.17 for P1 organization-scoped managers.

import django.db.models.manager
from django.db import migrations


P1_MODELS = (
    "contactactivity",
    "contractsigning",
    "contractsigningevent",
    "contractversion",
    "dataqualityissue",
    "dataqualityissueevent",
    "deallossoutcome",
    "dealworkstate",
    "lossreasoncode",
    "nextaction",
    "ownershiprelation",
    "ownershiprelationevent",
    "workflowauditevent",
)


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0011_p1_workflows"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name=model_name,
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        )
        for model_name in P1_MODELS
    ]
