# Generated by Django 5.2.17 for P2 decision evidence managers.

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0013_decision_evidence_snapshot"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="decisionevidencesnapshot",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
