# Generated by Django 5.2.17 for P2 map workbaskets.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid
import accounts.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forestry", "0005_remove_cadastrelabel_unique_cadastre_label_and_more"),
        ("operations", "0014_alter_decisionevidencesnapshot_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapWorkbasket",
            fields=[
                ("organization", models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="accounts.organization")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("purpose", models.CharField(blank=True, max_length=500)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("permission", models.CharField(choices=[("VIEW", "View"), ("EDIT", "Edit")], default="VIEW", max_length=10)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("PENDING", "Pending"), ("ACCEPTED", "Accepted"), ("CANCELLED", "Cancelled")], default="DRAFT", max_length=20)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accepted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="accepted_map_workbaskets", to=settings.AUTH_USER_MODEL)),
                ("assigned_to_role", models.CharField(blank=True, max_length=80)),
                ("assigned_to_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="assigned_map_workbaskets", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_map_workbaskets", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "p2_map_workbaskets",
                "ordering": ("-updated_at", "-created_at", "name"),
            },
        ),
        migrations.CreateModel(
            name="MapWorkbasketItem",
            fields=[
                ("organization", models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="accounts.organization")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("added_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="added_map_workbasket_items", to=settings.AUTH_USER_MODEL)),
                ("basket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="operations.mapworkbasket")),
                ("cadastre", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="map_workbasket_items", to="forestry.cadastre")),
            ],
            options={
                "db_table": "p2_map_workbasket_items",
                "ordering": ("sort_order", "added_at", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="mapworkbasket",
            index=models.Index(fields=["organization", "created_by", "status"], name="p2_workbasket_creator_idx"),
        ),
        migrations.AddIndex(
            model_name="mapworkbasket",
            index=models.Index(fields=["organization", "assigned_to_user", "status"], name="p2_workbasket_user_idx"),
        ),
        migrations.AddIndex(
            model_name="mapworkbasket",
            index=models.Index(fields=["organization", "assigned_to_role", "status"], name="p2_workbasket_role_idx"),
        ),
        migrations.AddIndex(
            model_name="mapworkbasketitem",
            index=models.Index(fields=["organization", "cadastre"], name="p2_workbasket_cadastre_idx"),
        ),
        migrations.AddConstraint(
            model_name="mapworkbasketitem",
            constraint=models.UniqueConstraint(fields=("organization", "basket", "cadastre"), name="p2_uq_workbasket_cadastre"),
        ),
        migrations.AlterModelManagers(
            name="mapworkbasket",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="mapworkbasketitem",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
