# Generated by Codex for P2 sales funnel probabilities and segments.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid
import accounts.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("operations", "0015_map_workbaskets"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesSegment",
            fields=[
                ("organization", models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="accounts.organization")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("filters", models.JSONField(default=dict)),
                ("is_shared", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_sales_segments", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "p2_sales_segments",
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="SalesStageProbability",
            fields=[
                ("organization", models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="accounts.organization")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("stage", models.CharField(max_length=20)),
                ("probability", models.DecimalField(decimal_places=4, max_digits=5)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_sales_stage_probabilities", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "p2_sales_stage_probabilities",
                "ordering": ("stage", "-valid_from", "-created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="salessegment",
            index=models.Index(fields=["organization", "created_by"], name="p2_sales_segment_creator_idx"),
        ),
        migrations.AddIndex(
            model_name="salessegment",
            index=models.Index(fields=["organization", "is_shared"], name="p2_sales_segment_shared_idx"),
        ),
        migrations.AddConstraint(
            model_name="salessegment",
            constraint=models.UniqueConstraint(fields=("organization", "created_by", "name"), name="p2_uq_sales_segment_owner_name"),
        ),
        migrations.AddIndex(
            model_name="salesstageprobability",
            index=models.Index(fields=["organization", "stage", "valid_from"], name="p2_sales_probability_idx"),
        ),
        migrations.AddConstraint(
            model_name="salesstageprobability",
            constraint=models.UniqueConstraint(fields=("organization", "stage", "valid_from"), name="p2_uq_sales_probability_stage_from"),
        ),
        migrations.AlterModelManagers(
            name="salessegment",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="salesstageprobability",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
