METSIS_PORT=9100
METSIS_DEVMODE=true
FINEFRAME_AUTH_USUAL_TOKEN_TTL_MIN=600
FINEFRAME_AUTH_REFRESH_TOKEN_TTL_MIN=600
FINEFRAME_AUTH_TOTP_TOKEN_TTL_MIN=2
FINEFRAME_DB_URL=jdbc:postgresql://localhost:5432/metsis
FINEFRAME_DB_USER=app
FINEFRAME_DB_PASSWORD=app

METSIS_BUYER_CODE=10828349
METSIS_BUYER_NAME=TM Energy OÜ
METSIS_BUYER_ADDRESS=Veski 17a Põltsamaa linn Jõgevamaa
METSIS_BUYER_MAIL=
METSIS_BUYER_PHONE=
METSIS_BUYER_PROXY_CODE=38805022784
METSIS_BUYER_PROXY_NAME=Kristo Piibe
METSIS_BUYER_PROXY_PHONE=
METSIS_BUYER_PROXY_MAIL=
METSIS_BUYER_PROXY_ADDRESS=
METSIS_BUYER_DAYS_TO_PAY_UP=10

METSIS_CONTRACT_DEFAULT_ADDITIONAL_TERMS=

METSIS_SIMO_API_ENDPOINT=
METSIS_SIMO_API_TOKEN=
