# Generated by Django 5.2.17 on 2026-08-22 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastre',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=50)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('registration_number', models.CharField(blank=True, db_column='reg_nr', max_length=50)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('postal', models.CharField(blank=True, max_length=100)),
                ('polygon', models.JSONField(blank=True, default=list)),
                ('centroid', models.JSONField(blank=True, default=dict)),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('arable_area', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('yard_area', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('meadow_area', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('forest_area', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('underwater_area', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('buildings_area', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('other_area', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('marked', models.BooleanField(default=False)),
                ('our_price', models.CharField(blank=True, max_length=255)),
                ('owners_price', models.CharField(blank=True, max_length=255)),
                ('mk_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cadastres',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='LastOwnersCadastresUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'last_owners_cadastres_update',
                'ordering': ('-event_time',),
            },
        ),
        migrations.CreateModel(
            name='OwnerStatus',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('days_out_of_search', models.PositiveIntegerField(db_column='days_out_of_search')),
                ('color_hex', models.CharField(db_column='reason_color', max_length=6)),
                ('protected', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'owner_statuses',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, choices=[('COUNTRY', 'Country'), ('PERSON', 'Person'), ('COMPANY', 'Company')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('info', models.TextField(blank=True)),
                ('out_of_admin_search_from', models.DateTimeField(blank=True, null=True)),
                ('out_of_admin_search_to', models.DateTimeField(blank=True, null=True)),
                ('out_of_admin_search_reason', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('status_set_at', models.DateTimeField(blank=True, null=True)),
                ('last_cadastre_list_refresh', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, db_column='caller_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_owners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'owners',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OwnerCadastre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastre', models.ForeignKey(db_column='cadastre_id', on_delete=django.db.models.deletion.CASCADE, to='forestry.cadastre')),
                ('owner', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, to='forestry.owner')),
            ],
            options={
                'db_table': 'owner_cadastre',
            },
        ),
        migrations.AddField(
            model_name='cadastre',
            name='owners',
            field=models.ManyToManyField(related_name='cadastres', through='forestry.OwnerCadastre', to='forestry.owner'),
        ),
        migrations.CreateModel(
            name='OwnerFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='forestry.owner')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'owner_followings',
            },
        ),
        migrations.CreateModel(
            name='OwnerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='timestamp')),
                ('creator', models.ForeignKey(db_column='creator', on_delete=django.db.models.deletion.PROTECT, related_name='owner_logs', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='forestry.owner')),
            ],
            options={
                'db_table': 'owner_log',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OwnerStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_status', models.CharField(blank=True, max_length=100)),
                ('to_status', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_owner_status_change_statistics',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='CadastreLabel',
            fields=[
                ('id', models.BigAutoField(db_column='pk', primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('CONSERVATION_AREA', 'Conservation area'), ('DEAD_LAND', 'Dead land'), ('SWAMP', 'Swamp'), ('REAL_ESTATE', 'Real estate'), ('NOTIFICATIONS_CONSUMED', 'Notifications consumed')], db_column='id', max_length=100)),
                ('cadastre', models.ForeignKey(db_column='cadastre_id', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='forestry.cadastre')),
            ],
            options={
                'db_table': 'cadastre_labels',
                'constraints': [models.UniqueConstraint(fields=('cadastre', 'code'), name='unique_cadastre_label')],
            },
        ),
        migrations.CreateModel(
            name='CadastreNotification',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('notification_number', models.BigIntegerField()),
                ('cadastre_subpart_code', models.IntegerField(blank=True, null=True)),
                ('work_code', models.CharField(blank=True, max_length=20)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('damage_code', models.CharField(blank=True, max_length=20)),
                ('decision', models.CharField(blank=True, max_length=20)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('amount_to_be_cut', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('archive_date', models.DateTimeField(blank=True, null=True)),
                ('cadastre', models.ForeignKey(db_column='cadastre_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='forestry.cadastre')),
            ],
            options={
                'db_table': 'cadastre_notifications',
                'ordering': ('-registration_date', '-id'),
                'indexes': [models.Index(fields=['cadastre', 'archived'], name='notification_archive_idx')],
            },
        ),
        migrations.CreateModel(
            name='CadastreSubPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_part_code', models.IntegerField(blank=True, null=True)),
                ('tree_type_code', models.CharField(blank=True, max_length=20)),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('polygon', models.JSONField(blank=True, default=list)),
                ('cadastre', models.ForeignKey(db_column='cadastre_id', on_delete=django.db.models.deletion.CASCADE, related_name='sub_parts', to='forestry.cadastre')),
            ],
            options={
                'db_table': 'cadastre_sub_parts',
                'constraints': [models.UniqueConstraint(fields=('cadastre', 'sub_part_code'), name='unique_cadastre_subpart')],
            },
        ),
        migrations.CreateModel(
            name='ForestRegistryFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_layer', models.CharField(max_length=100)),
                ('source_id', models.CharField(max_length=100)),
                ('subpart_code', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('work_code', models.CharField(blank=True, max_length=50)),
                ('decision', models.CharField(blank=True, max_length=100)),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('geometry', models.JSONField(blank=True, default=dict)),
                ('cadastre', models.ForeignKey(db_column='cadastre_id', on_delete=django.db.models.deletion.CASCADE, related_name='registry_features', to='forestry.cadastre')),
            ],
            options={
                'db_table': 'forest_registry_features',
                'indexes': [models.Index(fields=['cadastre', 'source_layer'], name='registry_cadastre_layer_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_layer', 'source_id'), name='unique_registry_source')],
            },
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['status'], name='owners_status_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['assignee'], name='owners_assignee_idx'),
        ),
        migrations.AddConstraint(
            model_name='ownercadastre',
            constraint=models.UniqueConstraint(fields=('owner', 'cadastre'), name='unique_owner_cadastre'),
        ),
        migrations.AddIndex(
            model_name='cadastre',
            index=models.Index(fields=['county', 'municipality'], name='cadastre_location_idx'),
        ),
        migrations.AddConstraint(
            model_name='ownerfollowing',
            constraint=models.UniqueConstraint(fields=('owner', 'user'), name='unique_owner_follower'),
        ),
    ]
