# Generated by Django 5.2.17 on 2026-08-26 07:47

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_user_default_organization_and_more'),
        ('forestry', '0004_subpart_discovered_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cadastrelabel',
            name='unique_cadastre_label',
        ),
        migrations.RemoveConstraint(
            model_name='cadastresubpart',
            name='unique_cadastre_subpart',
        ),
        migrations.RemoveConstraint(
            model_name='forestregistryfeature',
            name='unique_registry_source',
        ),
        migrations.RemoveConstraint(
            model_name='inheritancesignal',
            name='unique_inheritance_notice_cadastre',
        ),
        migrations.RemoveConstraint(
            model_name='ownercadastre',
            name='unique_owner_cadastre',
        ),
        migrations.RemoveConstraint(
            model_name='ownerfollowing',
            name='unique_owner_follower',
        ),
        migrations.RemoveIndex(
            model_name='cadastre',
            name='cadastre_location_idx',
        ),
        migrations.RemoveIndex(
            model_name='cadastrenotification',
            name='notification_archive_idx',
        ),
        migrations.RemoveIndex(
            model_name='datasyncrun',
            name='sync_run_cadastre_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='forestregistryfeature',
            name='registry_cadastre_layer_idx',
        ),
        migrations.RemoveIndex(
            model_name='inheritancesignal',
            name='inheritance_owner_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='owner',
            name='owners_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='owner',
            name='owners_assignee_idx',
        ),
        migrations.AddField(
            model_name='cadastre',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='cadastrelabel',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='cadastrenotification',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='cadastresubpart',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='datasyncrun',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='forestregistryfeature',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='inheritancesignal',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='lastownerscadastresupdate',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='owner',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='ownercadastre',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='ownerfollowing',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='ownerlog',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='ownerstatus',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='ownerstatuschange',
            name='organization',
            field=models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddIndex(
            model_name='cadastre',
            index=models.Index(fields=['organization', 'county', 'municipality'], name='cad_org_location_idx'),
        ),
        migrations.AddIndex(
            model_name='cadastrenotification',
            index=models.Index(fields=['organization', 'cadastre', 'archived'], name='notif_org_archive_idx'),
        ),
        migrations.AddIndex(
            model_name='datasyncrun',
            index=models.Index(fields=['organization', 'cadastre', 'status'], name='sync_run_org_cad_idx'),
        ),
        migrations.AddIndex(
            model_name='forestregistryfeature',
            index=models.Index(fields=['organization', 'cadastre', 'source_layer'], name='registry_org_cad_idx'),
        ),
        migrations.AddIndex(
            model_name='inheritancesignal',
            index=models.Index(fields=['organization', 'owner', 'announcement_date'], name='inheritance_org_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['organization', 'status'], name='owners_organization_status_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['organization', 'assignee'], name='owners_org_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='ownerlog',
            index=models.Index(fields=['organization', 'owner', 'created_at'], name='owner_log_org_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='ownerstatuschange',
            index=models.Index(fields=['organization', 'user', 'timestamp'], name='owner_status_change_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='cadastre',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='unique_cadastre_organization_id'),
        ),
        migrations.AddConstraint(
            model_name='cadastrelabel',
            constraint=models.UniqueConstraint(fields=('organization', 'cadastre', 'code'), name='unique_organization_cadastre_label'),
        ),
        migrations.AddConstraint(
            model_name='cadastresubpart',
            constraint=models.UniqueConstraint(fields=('organization', 'cadastre', 'sub_part_code'), name='unique_organization_cadastre_subpart'),
        ),
        migrations.AddConstraint(
            model_name='forestregistryfeature',
            constraint=models.UniqueConstraint(fields=('organization', 'source_layer', 'source_id'), name='unique_organization_registry_source'),
        ),
        migrations.AddConstraint(
            model_name='inheritancesignal',
            constraint=models.UniqueConstraint(fields=('organization', 'source_notice_number', 'cadastre'), name='unique_organization_inheritance_notice'),
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='unique_owner_organization_id'),
        ),
        migrations.AddConstraint(
            model_name='ownercadastre',
            constraint=models.UniqueConstraint(fields=('organization', 'owner', 'cadastre'), name='unique_organization_owner_cadastre'),
        ),
        migrations.AddConstraint(
            model_name='ownerfollowing',
            constraint=models.UniqueConstraint(fields=('organization', 'owner', 'user'), name='unique_organization_owner_follower'),
        ),
        migrations.AddConstraint(
            model_name='ownerstatus',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='unique_owner_status_organization_id'),
        ),
    ]
