# Generated by Django 5.2.17 on 2026-08-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestry', '0006_alter_cadastre_managers_alter_cadastrelabel_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='version',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
