# Generated by Django 5.2.17 on 2026-08-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestry', '0007_add_aggregate_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasyncrun',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
