# Generated by Django 5.2.17 on 2026-08-27 07:34

import accounts.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_oidc_subject'),
        ('forestry', '0008_add_datasyncrun_correlation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('source_layer', models.CharField(max_length=200)),
                ('cursor', models.PositiveIntegerField(default=0)),
                ('pages_completed', models.PositiveIntegerField(default=0)),
                ('rows_completed', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
                ('checkpointed_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_checkpoints', to='forestry.datasyncrun')),
                ('organization', models.ForeignKey(default=accounts.models.default_organization_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'import_checkpoints',
                'ordering': ('-checkpointed_at', '-id'),
                'indexes': [models.Index(fields=['organization', 'source', 'source_layer', 'completed'], name='import_checkpoint_lookup_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
