# Generated by Django 5.2.17 on 2026-08-27 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def convert_succeeded_runs_to_success(apps, schema_editor):
    """Preserve existing successful audit history under the normalized status."""

    DataSyncRun = apps.get_model("forestry", "DataSyncRun")
    DataSyncRun.objects.filter(status="SUCCEEDED").update(status="SUCCESS")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_oidc_subject'),
        ('forestry', '0009_add_import_checkpoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datasyncrun',
            name='backlog_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasyncrun',
            name='cursor',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='datasyncrun',
            name='lag_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasyncrun',
            name='pages_processed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasyncrun',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasyncrun',
            name='retry_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_runs', to='forestry.datasyncrun'),
        ),
        migrations.AddField(
            model_name='datasyncrun',
            name='rows_processed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datasyncrun',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='QUEUED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='datasyncrun',
            index=models.Index(fields=['organization', 'source', 'status'], name='sync_run_org_source_idx'),
        ),
        migrations.RunPython(convert_succeeded_runs_to_success, migrations.RunPython.noop),
    ]
