# Generated by Django 5.2.17 on 2026-08-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_oidc_subject'),
        ('forestry', '0010_expand_sync_run_audit'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cadastre',
            index=models.Index(fields=['organization', 'id'], name='cad_org_id_idx'),
        ),
        migrations.AddIndex(
            model_name='cadastrenotification',
            index=models.Index(fields=['organization', 'cadastre'], name='notif_org_cad_idx'),
        ),
        migrations.AddIndex(
            model_name='cadastresubpart',
            index=models.Index(fields=['organization', 'cadastre'], name='subpart_org_cad_idx'),
        ),
    ]
